const SNOWFLAKE_USER = 'interview_user'
const SNOWFLAKE_PASSWORD = 'yHsrH^%M#7Lf'
const SNOWFLAKE_ENDPOINT = 'gza68067'
const SNOWFLAKE_ROLE = 'interview_rl'
const SNOWFLAKE_WAREHOUSE = 'interview_wh'
const SNOWFLAKE_DATABASE = 'interview_db'

module.exports = {
  SNOWFLAKE_USER,
  SNOWFLAKE_PASSWORD,
  SNOWFLAKE_ENDPOINT,
  SNOWFLAKE_ROLE,
  SNOWFLAKE_WAREHOUSE,
  SNOWFLAKE_DATABASE
}
